### ISSUE TITLE
Webconsole crashes when receiving GET subscribers call

### ISSUE THREAD

**Issue by gruyaume** [omec-project/webconsole#88]
## Description

When receiving a GET call to all subscribers after a subscriber, a device group and a network slice, Webcolsole crashes and returns a 500 error code.

## To reproduce
1. Deploy SD-Core with webui
2. Create a new subscriber: `curl -v ${WEBUI_IP}:5000/api/subscriber/imsi-208930100007487 \
--header 'Content-Type: text/plain' \
--data '{
    "UeId":"208930100007487",
    "opc":"981d464c7c52eb6e5036234984ad0bcf",
    "key":"5122250214c33e723a5dd523fc145fc0",
    "sequenceNumber":"16f3b3f70fc2"
}'`
3. Create a new device group: `curl -v ${WEBUI_IP}:5000/config/v1/device-group/cows \
--header 'Content-Type: application/json' \
--data '{
    "imsis": [
        "208930100007487"
    ],
    "site-info": "demo",
    "ip-domain-name": "pool1",
    "ip-domain-expanded": {
        "dnn": "internet",
        "ue-ip-pool": "172.250.1.0/16",
        "dns-primary": "8.8.8.8",
        "mtu": 1460,
        "ue-dnn-qos": {
            "dnn-mbr-uplink": 20000000,
            "dnn-mbr-downlink": 200000000,
            "bitrate-unit": "bps",
            "traffic-class": {
                "name": "platinum",
                "arp": 6,
                "pdb": 300,
                "pelr": 6,
                "qci": 8
            }
        }
    }
}'`
4. Create a new network slice: `curl -v ${WEBUI_IP}:5000/config/v1/network-slice/default \
--header 'Content-Type: application/json' \
--data '{
  "slice-id": {
    "sst": "1",
    "sd": "010203"
  },
  "site-device-group": [
    "cows"
  ],
  "site-info": {
    "site-name": "demo",
    "plmn": {
      "mcc": "208",
      "mnc": "93"
    },
    "gNodeBs": [
      {
        "name": "demo-gnb1",
        "tac": 1
      }
    ],
    "upf": {
      "upf-name": "upf-external",
      "upf-port": "8805"
    }
  }
}'`
5. Get all subscribers: `curl -v --location ${WEBUI_IP}:5000/api/subscriber`

## Environment
- MicroK8s: 1.27
- Webui version: commit a21ec74683b7c1acf05366575f19c4102c54b9a2

## Logs

```
2023-11-28T21:21:37.516Z [webui] 2023-11-28T21:21:37Z [INFO][WebUI][WebUI] Get All Subscribers List
2023-11-28T21:21:37.516Z [webui] 2023-11-28T21:21:37Z [ERRO][WebUI][GIN] [Debugging] panic:
2023-11-28T21:21:37.516Z [webui] GET /api/subscriber HTTP/1.1
2023-11-28T21:21:37.516Z [webui] Host: 10.1.182.15:5000
2023-11-28T21:21:37.516Z [webui] Accept: */*
2023-11-28T21:21:37.516Z [webui] User-Agent: curl/8.1.2
2023-11-28T21:21:37.516Z [webui] 
2023-11-28T21:21:37.516Z [webui] 
2023-11-28T21:21:37.516Z [webui] interface conversion: interface {} is nil, not string
2023-11-28T21:21:37.516Z [webui] goroutine 245 [running]:
2023-11-28T21:21:37.516Z [webui] runtime/debug.Stack()
2023-11-28T21:21:37.516Z [webui] 	/snap/go/10426/src/runtime/debug/stack.go:24 +0x5e
2023-11-28T21:21:37.516Z [webui] github.com/omec-project/logger_util.NewGinWithLogrus.ginRecover.func2.1()
2023-11-28T21:21:37.516Z [webui] 	/root/go/pkg/mod/github.com/omec-project/logger_util@v1.1.0/logger_util.go:212 +0x117
2023-11-28T21:21:37.516Z [webui] panic({0xd0ea00?, 0xc0001492c0?})
2023-11-28T21:21:37.516Z [webui] 	/snap/go/10426/src/runtime/panic.go:914 +0x21f
2023-11-28T21:21:37.516Z [webui] github.com/omec-project/webconsole/configapi.GetSubscribers(0x3?)
2023-11-28T21:21:37.516Z [webui] 	/root/parts/webui/build/configapi/api_sub_config.go:283 +0x2bf
2023-11-28T21:21:37.516Z [webui] github.com/gin-gonic/gin.(*Context).Next(0xc00050c100)
2023-11-28T21:21:37.516Z [webui] 	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/context.go:173 +0x2b
2023-11-28T21:21:37.516Z [webui] github.com/omec-project/logger_util.NewGinWithLogrus.ginRecover.func2(0x7f38e80e4f70?)
2023-11-28T21:21:37.516Z [webui] 	/root/go/pkg/mod/github.com/omec-project/logger_util@v1.1.0/logger_util.go:244 +0x57
2023-11-28T21:21:37.516Z [webui] github.com/gin-gonic/gin.(*Context).Next(0xc00050c100)
2023-11-28T21:21:37.516Z [webui] 	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/context.go:173 +0x2b
2023-11-28T21:21:37.516Z [webui] github.com/omec-project/logger_util.NewGinWithLogrus.ginToLogrus.func1(0xc00050c100)
2023-11-28T21:21:37.516Z [webui] 	/root/go/pkg/mod/github.com/omec-project/logger_util@v1.1.0/logger_util.go:179 +0x5f
2023-11-28T21:21:37.516Z [webui] github.com/gin-gonic/gin.(*Context).Next(...)
2023-11-28T21:21:37.516Z [webui] 	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/context.go:173
2023-11-28T21:21:37.516Z [webui] github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc000103520, 0xc00050c100)
2023-11-28T21:21:37.516Z [webui] 	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/gin.go:616 +0x65b
2023-11-28T21:21:37.516Z [webui] github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc000103520, {0xfc0870?, 0xc0001520e0}, 0xc00050c000)
2023-11-28T21:21:37.516Z [webui] 	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/gin.go:572 +0x1dd
2023-11-28T21:21:37.516Z [webui] net/http.serverHandler.ServeHTTP({0xc0008013b0?}, {0xfc0870?, 0xc0001520e0?}, 0x6?)
2023-11-28T21:21:37.516Z [webui] 	/snap/go/10426/src/net/http/server.go:2938 +0x8e
2023-11-28T21:21:37.516Z [webui] net/http.(*conn).serve(0xc0005e62d0, {0xfc1dc8, 0xc000019f50})
2023-11-28T21:21:37.516Z [webui] 	/snap/go/10426/src/net/http/server.go:2009 +0x5f4
2023-11-28T21:21:37.516Z [webui] created by net/http.(*Server).Serve in goroutine 11
2023-11-28T21:21:37.516Z [webui] 	/snap/go/10426/src/net/http/server.go:3086 +0x5cb
```

**Comment by ghislainbourgeois** [comment]
This issue is probably caused by #84 as our version runs with that patch applied, and the line numbers seem to match with changes from that PR.

**Comment by thakurajayL** [comment]
I can take look at this next week. Let me know if someone has already started looking at it.

**Comment by gruyaume** [comment]
We found the issue, indeed it was related to a patch we were applying on our version of webui.
